export const CONSTANTS = {
    LANG: "ru",
    HEADER_TEXT: "To Do list",
    TASK_PLACEHOLDER: "Название",
    COMMENT_PLACEHOLDER: "Комментарий",
    WORKER_PLACEHOLDER: "Имя выполняющего",
    TIME_PLACEHOLDER: "Deadline",
    ADD_TASK_BUTTON: "Создать",
    COMPLETE_BUTTON: "Завершить",
    UNDO_BUTTON: "Редактировать",
    DELETE_BUTTON: "Удалить",
    EMPTY_TASK_LIST: "Никаих задач не создано",
    TASK_NAME_LABEL: "Название",
    WORKER_NAME_LABEL: "Имя выполняющего",
    DEADLINE_LABEL: "Сроки до",
};